- id: prettier
  name: prettier
  description: Run prettier to format supported files
  entry: prettier-pre-commit
  language: python
  types_or: [json, yaml, markdown, toml]
  require_serial: false
  additional_dependencies: []
