- id: prettier-format
  name: prettier-format
  description: "Format files with Prettier (JS, TS, CSS, HTML, JSON, YAML, Markdown, and more)"
  entry: prettier-format
  language: node
  files: \.(cjs|css|cts|es6?|gql|graphqls?|handlebars|hbs|html?|js|jsx?|json5?c?|less|livemd|mdx?|m(ark)?down|mdwn|mk(d|dn|down)|mjml|mjs|mts|pcss|postcss|scss|toml|tsx?|vue|xht(ml)?|ya?ml)$
  args: ["--write", "--ignore-unknown"]
  minimum_pre_commit_version: "3.0.0"
