name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Get current version and increment patch
        id: version
        shell: bash
        run: |
          set -euo pipefail
          CURRENT_VERSION=$(jq -r '.version // "1.0.0"' package.json)
          # Extract X.Y.Z (ignore prerelease/build metadata if present)
          core="${CURRENT_VERSION%%-*}"; core="${CURRENT_VERSION%%+*}"
          IFS='.' read -r MAJOR MINOR PATCH <<< "${core:-0.0.0}"
          : "${MAJOR:=0}" "${MINOR:=0}" "${PATCH:=0}"
          NEW_VERSION="${MAJOR}.${MINOR}.$((PATCH + 1))"
          echo "new_version=$NEW_VERSION" >> "$GITHUB_OUTPUT"
          echo "Incrementing version from $CURRENT_VERSION to $NEW_VERSION"

      - name: Update package.json version
        shell: bash
        run: |
          set -euo pipefail
          NEW_VERSION='${{ steps.version.outputs.new_version }}'
          jq --arg nv "$NEW_VERSION" '.version = $nv' package.json > package.json.tmp
          mv package.json.tmp package.json

      - name: Commit and tag
        shell: bash
        run: |
          set -euo pipefail
          NEW_VERSION='${{ steps.version.outputs.new_version }}'
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add package.json
          git commit -m "chore: bump version to v$NEW_VERSION"
          git tag -a "v$NEW_VERSION" -m "Release v$NEW_VERSION"
          git push origin main --follow-tags

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          NEW_VERSION='${{ steps.version.outputs.new_version }}'
          gh release create "v$NEW_VERSION" \
            --title "v$NEW_VERSION" \
            --generate-notes
